// Code generated by hertz generator.

package cache_variable_server

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setvalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletevalueMw() []app.HandlerFunc {
	// your code...
	return nil
}
