// Code generated by hertz generator.

package http_server

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "qinglin.org/cache_variable/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
