// Code generated by hertz generator. DO NOT EDIT.

package http_server

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"qinglin.org/cache_variable/biz/router"
)

// register registers all routers.
func Register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)
}
